version: "3.9"

services:
  postgres:
    image: bitnami/postgresql:17.2.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pichau
    volumes:
      - polls_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/postgresql:17.2.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - polls_redis_data:/bitnami/redis/data


volumes:
  polls_pg_data:
  polls_redis_data: